EXPECTED = {'functions': {'magnitude': {'params': [('z', 'ℂ')],
                             'return_type': 'ℝ',
                             'body': ('call', 'abs', [('var', 'z')]),
                             'has_loop': False,
                             'statements': []}},
 'classes': {},
 'program': [('decl', 'x', 'ℂ', ('add', ('num', 3), ('num', 1j)), 4),
             ('decl', 'y', 'ℂ', ('add', ('num', 5), ('num', 3j)), 5),
             ('expr', ('var', 'x'), 0),
             ('expr', ('var', 'y'), 0),
             ('assign', 'complex_add', ('add', ('var', 'x'), ('var', 'y')), 12),
             ('expr', ('var', 'complex_add'), 0),
             ('expr', ('sub', ('var', 'x'), ('var', 'y')), 0),
             ('assign', 'complex_mul', ('mul', ('var', 'x'), ('var', 'y')), 31),
             ('expr', ('var', 'complex_mul'), 0),
             ('func_def', 'magnitude'),
             ('expr', ('call', 'magnitude', [('var', 'x')]), 0),
             ('decl',
              'array_imag',
              'ℂ',
              ('array', [('num', 1j), ('num', 2j), ('num', 3j)]),
              58),
             ('decl',
              'array_complex',
              'ℂ',
              ('array',
               [('add', ('num', 1), ('num', 9j)),
                ('add', ('num', 7), ('num', 2j)),
                ('add', ('num', 3), ('num', 5j))]),
              60),
             ('decl',
              'nested_complex',
              'ℂ',
              ('array',
               [('array',
                 [('add', ('num', 1), ('num', 2j)),
                  ('add', ('num', 3), ('num', 4j))]),
                ('array',
                 [('add', ('num', 4), ('num', 9j)),
                  ('add', ('num', 7), ('num', 2j))])]),
              62),
             ('expr', ('var', 'array_imag'), 0),
             ('expr', ('var', 'array_complex'), 0),
             ('expr', ('var', 'nested_complex'), 0)]}
