EXPECTED = {'functions': {},
 'classes': {},
 'program': [('decl',
              'x',
              ('tensor', [(6, 'invariant')]),
              ('array',
               [('num', 1.0),
                ('num', 2.0),
                ('num', 3.0),
                ('num', 5.0),
                ('num', 6.0),
                ('num', 7.0)]),
              1),
             ('decl',
              'y',
              ('tensor', [(3, 'invariant')]),
              ('add',
               ('slice', 'x', ('num', 0.0), ('num', 2.0)),
               ('slice', 'x', ('num', 0.0), ('num', 2.0))),
              2),
             ('decl',
              'z',
              ('tensor', [(3, 'invariant')]),
              ('add', ('var', 'y'), ('array', [('num', 1.0), ('num', 3.0), ('num', 4.0)])),
              3),
             ('expr', ('var', 'x'), 0),
             ('expr', ('var', 'y'), 0),
             ('expr', ('var', 'z'), 0)]}
