EXPECTED = {'functions': {'magnitude': {'params': [('z', 'ℂ')],
                             'return_type': 'ℝ',
                             'body': ('call', 'abs', [('var', 'z')]),
                             'has_loop': False,
                             'statements': []}},
 'classes': {},
 'program': [('decl', 'x', 'ℂ', ('add', ('num', 3), ('num', 1j)), 2),
             ('decl', 'y', 'ℂ', ('add', ('num', 5), ('num', 3j)), 3),
             ('expr', ('var', 'x'), 0),
             ('expr', ('var', 'y'), 0),
             ('expr', ('add', ('var', 'x'), ('var', 'y')), 0),
             ('expr', ('sub', ('var', 'x'), ('var', 'y')), 0),
             ('expr', ('mul', ('var', 'x'), ('var', 'y')), 0),
             ('func_def', 'magnitude'),
             ('expr', ('call', 'magnitude', [('var', 'x')]), 0)]}
