EXPECTED = {'functions': {'f_vec': {'params': [('state',
                                     ('tensor', [('m', 'invariant')]))],
                         'return_type': ('tensor', [('m', 'invariant')]),
                         'body': ('array', [('var', 'fx'), ('var', 'fy')]),
                         'has_loop': False,
                         'statements': [('body_decl',
                                         'x',
                                         'ℝ',
                                         ('index', 'state', ('num', 0))),
                                        ('body_decl',
                                         'y',
                                         'ℝ',
                                         ('index', 'state', ('num', 1))),
                                        ('body_decl',
                                         'fx',
                                         'ℝ',
                                         ('add',
                                          ('pow', ('var', 'x'), ('num', 2)),
                                          ('var', 'y'))),
                                        ('body_decl',
                                         'fy',
                                         'ℝ',
                                         ('add',
                                          ('var', 'x'),
                                          ('pow', ('var', 'y'), ('num', 2))))]},
               'lotka_volterra': {'params': [('state',
                                              ('tensor', [('m', 'invariant')])),
                                             ('θ',
                                              ('tensor',
                                               [('n', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [('m', 'invariant')]),
                                  'body': ('array',
                                           [('var', 'dx'), ('var', 'dy')]),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'x',
                                                  'ℝ',
                                                  ('index',
                                                   'state',
                                                   ('num', 0))),
                                                 ('body_decl',
                                                  'y',
                                                  'ℝ',
                                                  ('index',
                                                   'state',
                                                   ('num', 1))),
                                                 ('body_decl',
                                                  'α',
                                                  'ℝ',
                                                  ('index', 'θ', ('num', 0))),
                                                 ('body_decl',
                                                  'β',
                                                  'ℝ',
                                                  ('index', 'θ', ('num', 1))),
                                                 ('body_decl',
                                                  'γ',
                                                  'ℝ',
                                                  ('index', 'θ', ('num', 2))),
                                                 ('body_decl',
                                                  'δ',
                                                  'ℝ',
                                                  ('index', 'θ', ('num', 3))),
                                                 ('body_decl',
                                                  'dx',
                                                  'ℝ',
                                                  ('sub',
                                                   ('mul',
                                                    ('var', 'α'),
                                                    ('var', 'x')),
                                                   ('mul',
                                                    ('mul',
                                                     ('var', 'β'),
                                                     ('var', 'x')),
                                                    ('var', 'y')))),
                                                 ('body_decl',
                                                  'dy',
                                                  'ℝ',
                                                  ('sub',
                                                   ('mul',
                                                    ('mul',
                                                     ('var', 'δ'),
                                                     ('var', 'x')),
                                                    ('var', 'y')),
                                                   ('mul',
                                                    ('var', 'γ'),
                                                    ('var', 'y'))))]}},
 'classes': {},
 'program': [('func_def', 'f_vec'),
             ('decl',
              'state',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0)]),
              16),
             ('decl',
              'J',
              ('tensor', [(2, 'invariant'), (2, 'invariant')]),
              ('call', 'grad', [('var', 'f_vec'), ('var', 'state')]),
              17),
             ('expr', ('var', 'J'), 0),
             ('func_def', 'lotka_volterra'),
             ('decl',
              'state',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 10.0), ('num', 1.0)]),
              32),
             ('decl',
              'θ',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 1.5), ('num', 1.0), ('num', 3.0), ('num', 1.0)]),
              33),
             ('decl',
              'J_state',
              ('tensor', [(2, 'invariant'), (2, 'invariant')]),
              ('call',
               'grad',
               [('var', 'lotka_volterra'),
                ('var', 'state'),
                ('var', 'θ'),
                ('num', 0)]),
              36),
             ('expr', ('var', 'J_state'), 0),
             ('decl',
              'J_theta',
              ('tensor', [(2, 'invariant'), (4, 'invariant')]),
              ('call',
               'grad',
               [('var', 'lotka_volterra'),
                ('var', 'state'),
                ('var', 'θ'),
                ('num', 1)]),
              40),
             ('expr', ('var', 'J_theta'), 0)]}
