EXPECTED = {'functions': {'f_vec': {'params': [('state', ('tensor', [(2, 'invariant')]))],
                         'return_type': ('tensor', [(2, 'invariant')]),
                         'body': ('array', [('var', 'fx'), ('var', 'fy')]),
                         'has_loop': False,
                         'statements': [('body_assign',
                                         'x',
                                         ('index', 'state', ('num', 0))),
                                        ('body_assign',
                                         'y',
                                         ('index', 'state', ('num', 1))),
                                        ('body_assign',
                                         'fx',
                                         ('add',
                                          ('pow', ('var', 'x'), ('num', 2)),
                                          ('var', 'y'))),
                                        ('body_assign',
                                         'fy',
                                         ('add',
                                          ('var', 'x'),
                                          ('pow', ('var', 'y'), ('num', 2))))]},
               'lotka_volterra': {'params': [('state',
                                              ('tensor', [(2, 'invariant')])),
                                             ('theta',
                                              ('tensor', [(4, 'invariant')]))],
                                  'return_type': ('tensor', [(2, 'invariant')]),
                                  'body': ('array',
                                           [('var', 'dx'), ('var', 'dy')]),
                                  'has_loop': False,
                                  'statements': [('body_assign',
                                                  'x',
                                                  ('index',
                                                   'state',
                                                   ('num', 0))),
                                                 ('body_assign',
                                                  'y',
                                                  ('index',
                                                   'state',
                                                   ('num', 1))),
                                                 ('body_assign',
                                                  'alpha',
                                                  ('index',
                                                   'theta',
                                                   ('num', 0))),
                                                 ('body_assign',
                                                  'beta',
                                                  ('index',
                                                   'theta',
                                                   ('num', 1))),
                                                 ('body_assign',
                                                  'gamma',
                                                  ('index',
                                                   'theta',
                                                   ('num', 2))),
                                                 ('body_assign',
                                                  'delta',
                                                  ('index',
                                                   'theta',
                                                   ('num', 3))),
                                                 ('body_assign',
                                                  'dx',
                                                  ('sub',
                                                   ('mul',
                                                    ('var', 'alpha'),
                                                    ('var', 'x')),
                                                   ('mul',
                                                    ('mul',
                                                     ('var', 'beta'),
                                                     ('var', 'x')),
                                                    ('var', 'y')))),
                                                 ('body_assign',
                                                  'dy',
                                                  ('sub',
                                                   ('mul',
                                                    ('mul',
                                                     ('var', 'delta'),
                                                     ('var', 'x')),
                                                    ('var', 'y')),
                                                   ('mul',
                                                    ('var', 'gamma'),
                                                    ('var', 'y'))))]}},
 'classes': {},
 'program': [('func_def', 'f_vec'),
             ('decl',
              'state',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0)]),
              15),
             ('assign',
              'J',
              ('call', 'grad', [('var', 'f_vec'), ('var', 'state')]),
              16),
             ('expr', ('var', 'J'), 0),
             ('func_def', 'lotka_volterra'),
             ('decl',
              'state',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 10.0), ('num', 1.0)]),
              31),
             ('decl',
              'theta',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 1.5), ('num', 1.0), ('num', 3.0), ('num', 1.0)]),
              32),
             ('assign',
              'J_state',
              ('call',
               'grad',
               [('var', 'lotka_volterra'),
                ('var', 'state'),
                ('var', 'theta'),
                ('num', 0)]),
              35),
             ('expr', ('var', 'J_state'), 0),
             ('assign',
              'J_theta',
              ('call',
               'grad',
               [('var', 'lotka_volterra'),
                ('var', 'state'),
                ('var', 'theta'),
                ('num', 1)]),
              39),
             ('expr', ('var', 'J_theta'), 0)]}
