EXPECTED = {'functions': {},
 'classes': {},
 'program': [('decl',
              'arr',
              ('tensor', [(5, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0), ('num', 5.0)]),
              7),
             ('decl', 'total', 'ℝ', ('num', 0.0), 8),
             ('for_loop',
              'i',
              [('for_pluseq', 'total', ('index', 'arr', ('imaginary',)))],
              ['arr'],
              9),
             ('expr', ('var', 'total'), 0),
             ('decl',
              'X',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)]),
              15),
             ('decl', 'sum_sq', 'ℝ', ('num', 0.0), 16),
             ('for_loop',
              'i',
              [('for_pluseq', 'sum_sq', ('pow', ('index', 'X', ('imaginary',)), ('num', 2.0)))],
              ['X'],
              17),
             ('expr', ('var', 'sum_sq'), 0),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 2.0), ('num', 4.0), ('num', 6.0), ('num', 8.0)]),
              22),
             ('decl', 'mse', 'ℝ', ('num', 0.0), 23),
             ('for_loop',
              'i',
              [('for_pluseq',
                'mse',
                ('pow',
                 ('sub', ('index', 'X', ('imaginary',)), ('index', 'y', ('imaginary',))),
                 ('num', 2.0)))],
              ['X', 'y'],
              24),
             ('expr', ('var', 'mse'), 0)]}
