EXPECTED = {'functions': {'U': {'params': [('k', 'ℝ'),
                                ('m', 'ℝ'),
                                ('t', 'ℝ'),
                                ('x0', 'ℝ'),
                                ('v0', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': ('add',
                              ('mul',
                               ('var', 'A'),
                               ('call',
                                'cos',
                                [('mul', ('var', 'omega'), ('var', 't'))])),
                              ('mul',
                               ('var', 'B'),
                               ('call',
                                'sin',
                                [('mul', ('var', 'omega'), ('var', 't'))]))),
                     'has_loop': False,
                     'statements': [('body_assign',
                                     'omega',
                                     ('pow',
                                      ('div', ('var', 'k'), ('var', 'm')),
                                      ('num', 0.5))),
                                    ('body_assign', 'A', ('var', 'x0')),
                                    ('body_assign',
                                     'B',
                                     ('div',
                                      ('var', 'v0'),
                                      ('var', 'omega')))]}},
 'classes': {},
 'program': [('func_def', 'U'),
             ('decl', 'k', 'ℝ', ('num', 1.0), 41),
             ('decl', 'm', 'ℝ', ('num', 1.0), 42),
             ('decl', 'x0', 'ℝ', ('num', 1.0), 45),
             ('decl', 'v0', 'ℝ', ('num', 0.0), 46),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 0.0),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 1.5708),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 3.1416),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 4.7124),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 6.2832),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 1.5708),
                ('num', 0.0),
                ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 3.1416),
                ('num', 0.0),
                ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'animate',
               [('var', 'U'),
                ('var', 'k'),
                ('var', 'm'),
                ('var', 'x0'),
                ('var', 'v0'),
                ('num', 0.0),
                ('num', 31.1416)]),
              0),
             ('decl', 't0', 'ℝ', ('num', 0.0), 83),
             ('expr',
              ('call',
               'grad',
               [('call',
                 'real',
                 [('call',
                   'U',
                   [('var', 'k'),
                    ('var', 'm'),
                    ('var', 't0'),
                    ('var', 'x0'),
                    ('var', 'v0')])]),
                ('var', 't0')]),
              0),
             ('decl', 't1', 'ℝ', ('num', 1.5708), 86),
             ('expr',
              ('call',
               'grad',
               [('call',
                 'real',
                 [('call',
                   'U',
                   [('var', 'k'),
                    ('var', 'm'),
                    ('var', 't1'),
                    ('var', 'x0'),
                    ('var', 'v0')])]),
                ('var', 't1')]),
              0),
             ('decl', 't2', 'ℝ', ('num', 3.1416), 89),
             ('expr',
              ('call',
               'grad',
               [('call',
                 'real',
                 [('call',
                   'U',
                   [('var', 'k'),
                    ('var', 'm'),
                    ('var', 't2'),
                    ('var', 'x0'),
                    ('var', 'v0')])]),
                ('var', 't2')]),
              0)]}
