EXPECTED = {'functions': {'factorial': {'params': [('n', 'ℕ')],
                             'return_type': 'ℝ',
                             'body': ('var', 'result'),
                             'has_loop': False,
                             'statements': [('body_decl',
                                             'result',
                                             'ℝ',
                                             ('num', 1.0)),
                                            ('body_for_range',
                                             'i',
                                             ('num', 1),
                                             ('add', ('var', 'n'), ('num', 1)),
                                             [('loop_assign',
                                               'result',
                                               ('mul',
                                                ('var', 'result'),
                                                ('imaginary',)))])]},
               'physika_cos': {'params': [('x', 'ℝ')],
                               'return_type': 'ℝ',
                               'body': ('var', 'result'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'n',
                                               'ℕ',
                                               ('num', 10)),
                                              ('body_decl',
                                               'result',
                                               'ℝ',
                                               ('num', 0.0)),
                                              ('body_for_range',
                                               'i',
                                               ('num', 0),
                                               ('var', 'n'),
                                               [('loop_assign',
                                                 'sign',
                                                 ('pow',
                                                  ('neg', ('num', 1)),
                                                  ('imaginary',))),
                                                ('loop_assign',
                                                 'power',
                                                 ('pow',
                                                  ('var', 'x'),
                                                  ('mul',
                                                   ('num', 2),
                                                   ('imaginary',)))),
                                                ('loop_assign',
                                                 'fact',
                                                 ('call',
                                                  'factorial',
                                                  [('mul',
                                                    ('num', 2),
                                                    ('imaginary',))])),
                                                ('loop_assign',
                                                 'result',
                                                 ('add',
                                                  ('var', 'result'),
                                                  ('div',
                                                   ('mul',
                                                    ('var', 'sign'),
                                                    ('var', 'power')),
                                                   ('var', 'fact'))))])]},
               'physika_sin': {'params': [('x', 'ℝ')],
                               'return_type': 'ℝ',
                               'body': ('var', 'result'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'n',
                                               'ℕ',
                                               ('num', 10)),
                                              ('body_decl',
                                               'result',
                                               'ℝ',
                                               ('num', 0.0)),
                                              ('body_for_range',
                                               'i',
                                               ('num', 0),
                                               ('var', 'n'),
                                               [('loop_assign',
                                                 'sign',
                                                 ('pow',
                                                  ('neg', ('num', 1)),
                                                  ('imaginary',))),
                                                ('loop_assign',
                                                 'power',
                                                 ('pow',
                                                  ('var', 'x'),
                                                  ('add',
                                                   ('mul',
                                                    ('num', 2),
                                                    ('imaginary',)),
                                                   ('num', 1)))),
                                                ('loop_assign',
                                                 'fact',
                                                 ('call',
                                                  'factorial',
                                                  [('add',
                                                    ('mul',
                                                     ('num', 2),
                                                     ('imaginary',)),
                                                    ('num', 1))])),
                                                ('loop_assign',
                                                 'result',
                                                 ('add',
                                                  ('var', 'result'),
                                                  ('div',
                                                   ('mul',
                                                    ('var', 'sign'),
                                                    ('var', 'power')),
                                                   ('var', 'fact'))))])]},
               'U': {'params': [('k', 'ℝ'),
                                ('m', 'ℝ'),
                                ('t', 'ℝ'),
                                ('x0', 'ℝ'),
                                ('v0', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': ('add',
                              ('mul',
                               ('var', 'A'),
                               ('call',
                                'physika_cos',
                                [('mul', ('var', 'omega'), ('var', 't'))])),
                              ('mul',
                               ('var', 'B'),
                               ('call',
                                'physika_sin',
                                [('mul', ('var', 'omega'), ('var', 't'))]))),
                     'has_loop': False,
                     'statements': [('body_assign',
                                     'omega',
                                     ('pow',
                                      ('div', ('var', 'k'), ('var', 'm')),
                                      ('num', 0.5))),
                                    ('body_assign', 'A', ('var', 'x0')),
                                    ('body_assign',
                                     'B',
                                     ('div',
                                      ('var', 'v0'),
                                      ('var', 'omega')))]}},
 'classes': {},
 'program': [('func_def', 'factorial'),
             ('func_def', 'physika_cos'),
             ('func_def', 'physika_sin'),
             ('func_def', 'U'),
             ('decl', 'k', 'ℝ', ('num', 1.0), 71),
             ('decl', 'm', 'ℝ', ('num', 1.0), 72),
             ('decl', 'x0', 'ℝ', ('num', 1.0), 75),
             ('decl', 'v0', 'ℝ', ('num', 0.0), 76),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 0.0),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 1.5708),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 3.1416),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 4.7124),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 6.2832),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 1.5708),
                ('num', 0.0),
                ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 3.1416),
                ('num', 0.0),
                ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'animate',
               [('var', 'U'),
                ('var', 'k'),
                ('var', 'm'),
                ('var', 'x0'),
                ('var', 'v0'),
                ('num', 0.0),
                ('num', 31.1416)]),
              0),
             ('decl', 't0', 'ℝ', ('num', 0.0), 113),
             ('expr',
              ('call',
               'grad',
               [('call',
                 'real',
                 [('call',
                   'U',
                   [('var', 'k'),
                    ('var', 'm'),
                    ('var', 't0'),
                    ('var', 'x0'),
                    ('var', 'v0')])]),
                ('var', 't0')]),
              0),
             ('decl', 't1', 'ℝ', ('num', 1.5708), 116),
             ('expr',
              ('call',
               'grad',
               [('call',
                 'real',
                 [('call',
                   'U',
                   [('var', 'k'),
                    ('var', 'm'),
                    ('var', 't1'),
                    ('var', 'x0'),
                    ('var', 'v0')])]),
                ('var', 't1')]),
              0),
             ('decl', 't2', 'ℝ', ('num', 3.1416), 119),
             ('expr',
              ('call',
               'grad',
               [('call',
                 'real',
                 [('call',
                   'U',
                   [('var', 'k'),
                    ('var', 'm'),
                    ('var', 't2'),
                    ('var', 'x0'),
                    ('var', 'v0')])]),
                ('var', 't2')]),
              0)]}
