EXPECTED = {'functions': {'U': {'params': [('k', 'ℝ'), ('m', 'ℝ'), ('t', 'ℝ'), ('x0', 'ℝ'), ('v0', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': ('add',
                              ('mul',
                               ('var', 'a'),
                               ('call',
                                'exp',
                                [('mul',
                                  ('mul', ('imaginary',), ('var', 't')),
                                  ('var', 'omega'))])),
                              ('mul',
                               ('var', 'b'),
                               ('call',
                                'exp',
                                [('sub',
                                  ('num', 0.0),
                                  ('mul',
                                   ('mul', ('imaginary',), ('var', 't')),
                                   ('var', 'omega')))]))),
                     'has_loop': False,
                     'statements': [('body_decl',
                                     'omega',
                                     'ℝ',
                                     ('pow', ('div', ('var', 'k'), ('var', 'm')), ('num', 0.5))),
                                    ('body_decl', 'eq1', 'ℝ', ('string', 'x0 = a + b')),
                                    ('body_decl',
                                     'eq2',
                                     'ℝ',
                                     ('string', 'v0 = i * omega * a - i * omega * b')),
                                    ('body_tuple_unpack',
                                     ['a', 'b'],
                                     ('call', 'solve', [('var', 'eq1'), ('var', 'eq2')]))]}},
 'classes': {},
 'program': [('func_def', 'U'),
             ('decl', 'k', 'ℝ', ('num', 1.0), 28),
             ('decl', 'm', 'ℝ', ('num', 1.0), 29),
             ('decl', 'x0', 'ℝ', ('num', 1.0), 32),
             ('decl', 'v0', 'ℝ', ('num', 0.0), 33),
             ('expr',
              ('call',
               'U',
               [('var', 'k'), ('var', 'm'), ('num', 0.0), ('var', 'x0'), ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'), ('var', 'm'), ('num', 1.5708), ('var', 'x0'), ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'), ('var', 'm'), ('num', 3.1416), ('var', 'x0'), ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'), ('var', 'm'), ('num', 4.7124), ('var', 'x0'), ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'), ('var', 'm'), ('num', 6.2832), ('var', 'x0'), ('var', 'v0')]),
              0),
             ('expr',
              ('call', 'U', [('var', 'k'), ('var', 'm'), ('num', 0.0), ('num', 0.0), ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'), ('var', 'm'), ('num', 1.5708), ('num', 0.0), ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'), ('var', 'm'), ('num', 3.1416), ('num', 0.0), ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'animate',
               [('var', 'U'),
                ('var', 'k'),
                ('var', 'm'),
                ('var', 'x0'),
                ('var', 'v0'),
                ('num', 0.0),
                ('num', 31.1416)]),
              0),
             ('decl', 't0', 'ℝ', ('num', 0.0), 70),
             ('expr',
              ('call',
               'grad',
               [('call',
                 'real',
                 [('call',
                   'U',
                   [('var', 'k'), ('var', 'm'), ('var', 't0'), ('var', 'x0'), ('var', 'v0')])]),
                ('var', 't0')]),
              0),
             ('decl', 't1', 'ℝ', ('num', 1.5708), 73),
             ('expr',
              ('call',
               'grad',
               [('call',
                 'real',
                 [('call',
                   'U',
                   [('var', 'k'), ('var', 'm'), ('var', 't1'), ('var', 'x0'), ('var', 'v0')])]),
                ('var', 't1')]),
              0),
             ('decl', 't2', 'ℝ', ('num', 3.1416), 76),
             ('expr',
              ('call',
               'grad',
               [('call',
                 'real',
                 [('call',
                   'U',
                   [('var', 'k'), ('var', 'm'), ('var', 't2'), ('var', 'x0'), ('var', 'v0')])]),
                ('var', 't2')]),
              0)]}
