EXPECTED = {'classes': {'HamiltonianNet': {'body': ('var', 'h'),
                                'class_params': [('W1',
                                                  ('tensor',
                                                   [('M', 'invariant'),
                                                    ('N', 'invariant')])),
                                                 ('b1',
                                                  ('tensor',
                                                   [('M', 'invariant')])),
                                                 ('w2',
                                                  ('tensor',
                                                   [('M', 'invariant')])),
                                                 ('b2', 'ℝ')],
                                'has_loop': False,
                                'has_loss': True,
                                'lambda_params': [('x',
                                                   ('tensor',
                                                    [('N', 'invariant')]))],
                                'loss_body': ('var', 'lo'),
                                'loss_params': [('H', 'ℝ'),
                                                ('target',
                                                 ('tensor',
                                                  [('N', 'invariant')]))],
                                'loss_statements': [('body_decl',
                                                     'lo',
                                                     'ℝ',
                                                     ('add',
                                                      ('pow',
                                                       ('sub',
                                                        ('call_index',
                                                         'grad',
                                                         [('var', 'H'),
                                                          ('var', 'x')],
                                                         ('num', 1)),
                                                        ('index',
                                                         'target',
                                                         ('num', 0))),
                                                       ('num', 2.0)),
                                                      ('pow',
                                                       ('sub',
                                                        ('sub',
                                                         ('num', 0.0),
                                                         ('call_index',
                                                          'grad',
                                                          [('var', 'H'),
                                                           ('var', 'x')],
                                                          ('num', 0))),
                                                        ('index',
                                                         'target',
                                                         ('num', 1))),
                                                       ('num', 2.0))))],
                                'return_type': 'ℝ',
                                'statements': [('body_decl',
                                                'h',
                                                'ℝ',
                                                ('add',
                                                 ('matmul',
                                                  ('var', 'w2'),
                                                  ('call',
                                                   'tanh',
                                                   [('add',
                                                     ('matmul',
                                                      ('var', 'W1'),
                                                      ('var', 'x')),
                                                     ('var', 'b1'))])),
                                                 ('var', 'b2')))]}},
 'functions': {'tanh': {'body': ('div',
                                 ('sub',
                                  ('call', 'exp', [('var', 'x')]),
                                  ('call',
                                   'exp',
                                   [('sub', ('num', 0.0), ('var', 'x'))])),
                                 ('add',
                                  ('call', 'exp', [('var', 'x')]),
                                  ('call',
                                   'exp',
                                   [('sub', ('num', 0.0), ('var', 'x'))]))),
                        'has_loop': False,
                        'params': [('x', 'ℝ')],
                        'return_type': 'ℝ',
                        'statements': []}},
 'program': [('func_def', 'tanh'),
             ('class_def', 'HamiltonianNet'),
             ('decl',
              'X',
              ('tensor', [(8, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 0.0), ('num', 1.0)]),
                ('array', [('num', 1.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('neg', ('num', 1.0))]),
                ('array', [('neg', ('num', 1.0)), ('num', 0.0)]),
                ('array', [('num', 0.5), ('num', 0.5)]),
                ('array', [('neg', ('num', 0.5)), ('neg', ('num', 0.5))]),
                ('array', [('num', 0.7), ('neg', ('num', 0.7))]),
                ('array', [('neg', ('num', 0.7)), ('num', 0.7)])]),
              31),
             ('decl',
              'y',
              ('tensor', [(8, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('neg', ('num', 1.0))]),
                ('array', [('neg', ('num', 1.0)), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 1.0)]),
                ('array', [('num', 0.5), ('neg', ('num', 0.5))]),
                ('array', [('neg', ('num', 0.5)), ('num', 0.5)]),
                ('array', [('neg', ('num', 0.7)), ('neg', ('num', 0.7))]),
                ('array', [('num', 0.7), ('num', 0.7)])]),
              33),
             ('decl',
              'W1',
              ('tensor', [(16, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 0.5), ('num', 0.1)]),
                ('array', [('num', 0.1), ('num', 0.5)]),
                ('array', [('num', 0.3), ('num', 0.3)]),
                ('array', [('num', 0.4), ('num', 0.2)]),
                ('array', [('num', 0.2), ('num', 0.4)]),
                ('array', [('num', 0.1), ('num', 0.1)]),
                ('array', [('num', 0.3), ('num', 0.1)]),
                ('array', [('num', 0.1), ('num', 0.3)]),
                ('array', [('num', 0.2), ('num', 0.2)]),
                ('array', [('num', 0.4), ('num', 0.4)]),
                ('array', [('num', 0.5), ('num', 0.3)]),
                ('array', [('num', 0.3), ('num', 0.5)]),
                ('array', [('num', 0.2), ('num', 0.1)]),
                ('array', [('num', 0.1), ('num', 0.2)]),
                ('array', [('num', 0.4), ('num', 0.1)]),
                ('array', [('num', 0.1), ('num', 0.4)])]),
              39),
             ('decl',
              'b1',
              ('tensor', [(16, 'invariant')]),
              ('array',
               [('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0)]),
              43),
             ('decl',
              'w2',
              ('tensor', [(16, 'invariant')]),
              ('array',
               [('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1)]),
              45),
             ('decl', 'b2', 'ℝ', ('num', 0.0), 47),
             ('assign',
              'H_net',
              ('call',
               'HamiltonianNet',
               [('var', 'W1'), ('var', 'b1'), ('var', 'w2'), ('var', 'b2')]),
              49),
             ('assign',
              'loss_before',
              ('call',
               'evaluate',
               [('var', 'H_net'), ('var', 'X'), ('var', 'y')]),
              54),
             ('expr', ('var', 'loss_before'), 0),
             ('decl', 'epochs', 'ℕ', ('num', 500), 61),
             ('decl', 'lr', 'ℝ', ('num', 0.01), 62),
             ('assign',
              'H_trained',
              ('call',
               'train',
               [('var', 'H_net'),
                ('var', 'X'),
                ('var', 'y'),
                ('var', 'epochs'),
                ('var', 'lr')]),
              63),
             ('assign',
              'loss_after',
              ('call',
               'evaluate',
               [('var', 'H_trained'), ('var', 'X'), ('var', 'y')]),
              68),
             ('expr', ('var', 'loss_after'), 0)]}