EXPECTED = {'functions': {'H': {'params': [('J', 'ℝ'),
                                ('h', 'ℝ'),
                                ('spins', ('tensor', [('m', 'invariant')]))],
                     'return_type': 'ℝ',
                     'body': ('sub',
                              ('mul', ('neg', ('var', 'J')), ('var', 'nn_sum')),
                              ('mul', ('var', 'h'), ('var', 'field_sum'))),
                     'has_loop': False,
                     'statements': [('body_decl',
                                     'nn_products',
                                     ('tensor', [('n', 'invariant')]),
                                     ('for_expr',
                                      'i',
                                      ('sub', ('var', 'n'), ('num', 1)),
                                      ('mul',
                                       ('index', 'spins', ('imaginary',)),
                                       ('index',
                                        'spins',
                                        ('add', ('imaginary',), ('num', 1)))))),
                                    ('body_decl',
                                     'nn_sum',
                                     'ℝ',
                                     ('call', 'sum', [('var', 'nn_products')])),
                                    ('body_decl',
                                     'field_sum',
                                     'ℝ',
                                     ('call', 'sum', [('var', 'spins')]))]}},
 'classes': {},
 'program': [('decl', 'n', 'ℝ', ('num', 16.0), 3),
             ('decl', 'J', 'ℝ', ('num', 2.0), 4),
             ('decl', 'h', 'ℝ', ('num', 0.1), 5),
             ('decl', 'β', 'ℝ', ('num', 5.0), 6),
             ('sample',
              'b',
              ('call', 'Bernoulli', [('num', 0.5), ('var', 'n')]),
              10),
             ('decl',
              'spins',
              ('tensor', [('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('sub',
                ('mul', ('num', 2.0), ('index', 'b', ('imaginary',))),
                ('num', 1.0))),
              11),
             ('expr', ('var', 'spins'), 0),
             ('decl',
              'M',
              'ℝ',
              ('div', ('call', 'sum', [('var', 'spins')]), ('var', 'n')),
              15),
             ('expr', ('var', 'M'), 0),
             ('func_def', 'H'),
             ('expr',
              ('call', 'H', [('var', 'J'), ('var', 'h'), ('var', 'spins')]),
              0),
             ('decl',
              'log_p',
              'ℝ',
              ('mul',
               ('neg', ('var', 'β')),
               ('call', 'H', [('var', 'J'), ('var', 'h'), ('var', 'spins')])),
              30),
             ('expr', ('var', 'log_p'), 0),
             ('decl',
              'dH_dJ',
              'ℝ',
              ('call',
               'grad',
               [('call', 'H', [('var', 'J'), ('var', 'h'), ('var', 'spins')]),
                ('var', 'J')]),
              39),
             ('decl',
              'dH_dh',
              'ℝ',
              ('call',
               'grad',
               [('call', 'H', [('var', 'J'), ('var', 'h'), ('var', 'spins')]),
                ('var', 'h')]),
              40),
             ('expr', ('var', 'dH_dJ'), 0),
             ('expr', ('var', 'dH_dh'), 0)]}
