EXPECTED = {'functions': {},
 'classes': {},
 'program': [('decl', 'm_true', 'ℝ', ('num', 3.0), 4),
             ('decl', 'b_true', 'ℝ', ('num', 1.0), 5),
             ('decl', 'm_hat', 'ℝ', ('num', 2.0), 6),
             ('decl', 'b_hat', 'ℝ', ('num', 0.0), 7),
             ('decl', 'μ', 'ℝ', ('num', 2.0), 11),
             ('decl', 'σ', 'ℝ', ('num', 0.5), 12),
             ('decl', 'n', 'ℤ', ('num', 100), 15),
             ('typed_sample',
              'x',
              ('tensor', [('n', 'invariant')]),
              ('call', 'Normal', [('var', 'μ'), ('var', 'σ'), ('var', 'n')]),
              16),
             ('assign',
              'y_true',
              ('add',
               ('mul', ('var', 'm_true'), ('var', 'x')),
               ('var', 'b_true')),
              17),
             ('assign',
              'y_pred',
              ('add',
               ('mul', ('var', 'm_hat'), ('var', 'x')),
               ('var', 'b_hat')),
              18),
             ('decl',
              'loss',
              'ℝ',
              ('div',
               ('call',
                'sum',
                [('pow',
                  ('sub', ('var', 'y_pred'), ('var', 'y_true')),
                  ('num', 2))]),
               ('var', 'n')),
              19),
             ('expr', ('var', 'loss'), 0),
             ('decl',
              'grad_mu',
              'ℝ',
              ('call', 'grad', [('var', 'loss'), ('var', 'μ')]),
              22),
             ('decl',
              'grad_sigma',
              'ℝ',
              ('call', 'grad', [('var', 'loss'), ('var', 'σ')]),
              23),
             ('expr', ('var', 'grad_mu'), 0),
             ('expr', ('var', 'grad_sigma'), 0),
             ('decl', 'lr', 'ℝ', ('num', 0.01), 28),
             ('for_loop_range',
              'step',
              ('num', 0),
              ('num', 300),
              [('typed_sample',
                'x',
                ('tensor', [('n', 'invariant')]),
                ('call', 'Normal', [('var', 'μ'), ('var', 'σ'), ('var', 'n')])),
               ('for_assign',
                'y_true',
                ('add',
                 ('mul', ('var', 'm_true'), ('var', 'x')),
                 ('var', 'b_true'))),
               ('for_assign',
                'y_pred',
                ('add',
                 ('mul', ('var', 'm_hat'), ('var', 'x')),
                 ('var', 'b_hat'))),
               ('for_assign',
                'loss',
                ('div',
                 ('call',
                  'sum',
                  [('pow',
                    ('sub', ('var', 'y_pred'), ('var', 'y_true')),
                    ('num', 2))]),
                 ('var', 'n'))),
               ('for_assign',
                'grad_mu',
                ('call', 'grad', [('var', 'loss'), ('var', 'μ')])),
               ('for_assign',
                'grad_sigma',
                ('call', 'grad', [('var', 'loss'), ('var', 'σ')])),
               ('for_assign',
                'μ',
                ('sub',
                 ('var', 'μ'),
                 ('mul', ('var', 'lr'), ('var', 'grad_mu')))),
               ('for_assign',
                'σ',
                ('sub',
                 ('var', 'σ'),
                 ('mul', ('var', 'lr'), ('var', 'grad_sigma'))))],
              29),
             ('expr', ('var', 'μ'), 0),
             ('expr', ('var', 'σ'), 0),
             ('typed_sample',
              'x',
              ('tensor', [('n', 'invariant')]),
              ('call', 'Normal', [('var', 'μ'), ('var', 'σ'), ('var', 'n')]),
              43),
             ('assign',
              'y_true',
              ('add',
               ('mul', ('var', 'm_true'), ('var', 'x')),
               ('var', 'b_true')),
              44),
             ('assign',
              'y_pred',
              ('add',
               ('mul', ('var', 'm_hat'), ('var', 'x')),
               ('var', 'b_hat')),
              45),
             ('decl',
              'loss',
              'ℝ',
              ('div',
               ('call',
                'sum',
                [('pow',
                  ('sub', ('var', 'y_pred'), ('var', 'y_true')),
                  ('num', 2))]),
               ('var', 'n')),
              46),
             ('expr', ('var', 'loss'), 0),
             ('decl',
              'z',
              ('tensor', [(10, 'invariant'), (2, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 10),
               ('typed_sample_expr',
                'ε',
                ('tensor', [(2, 'invariant')]),
                ('call', 'Normal', [('var', 'μ'), ('var', 'σ'), ('num', 2)]))),
              50),
             ('expr', ('var', 'z'), 0),
             ('typed_sample',
              'y',
              ('tensor', [(10, 'invariant'), (10, 'invariant')]),
              ('call',
               'Normal',
               [('var', 'μ'), ('var', 'σ'), ('num', 10), ('num', 10)]),
              53),
             ('func_def', 'sample_normal'),
             ('decl', 'x', 'ℝ', ('num', 3), 61),
             ('expr', ('call', 'sample_normal', [('var', 'x')]), 0)]}
