EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'linspace': {'params': [('start', 'ℝ'),
                                       ('end', 'ℝ'),
                                       ('n', 'ℕ')],
                            'return_type': ('tensor', [('n', 'invariant')]),
                            'body': ('var', 'x'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'x',
                                            ('tensor', [('n', 'invariant')]),
                                            ('call',
                                             'zero_1d_array',
                                             [('var', 'n')])),
                                           ('body_decl',
                                            'Δx',
                                            'ℝ',
                                            ('div',
                                             ('sub',
                                              ('var', 'end'),
                                              ('var', 'start')),
                                             ('sub',
                                              ('var', 'n'),
                                              ('num', 1)))),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('var', 'n'),
                                            [('loop_index_assign_nd',
                                              'x',
                                              [('index_item', ('imaginary',))],
                                              ('add',
                                               ('var', 'start'),
                                               ('mul',
                                                ('imaginary',),
                                                ('var', 'Δx'))))])]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'central_difference_x': {'params': [('f',
                                                    ('tensor',
                                                     [('m', 'invariant'),
                                                      ('n', 'invariant')]))],
                                        'return_type': ('tensor',
                                                        [('m', 'invariant'),
                                                         ('n', 'invariant')]),
                                        'body': ('var', 'diff'),
                                        'has_loop': False,
                                        'statements': [('body_decl',
                                                        'diff',
                                                        ('tensor',
                                                         [('n_points',
                                                           'invariant'),
                                                          ('n_points',
                                                           'invariant')]),
                                                        ('call',
                                                         'zero_2d_array',
                                                         [('var', 'n_points'),
                                                          ('var',
                                                           'n_points')])),
                                                       ('body_index_assign_nd',
                                                        'diff',
                                                        [('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'n_points'),
                                                           ('num', 1))),
                                                         ('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'n_points'),
                                                           ('num', 1)))],
                                                        ('div',
                                                         ('sub',
                                                          ('indexN',
                                                           'f',
                                                           [('slice_item',
                                                             ('num', 1),
                                                             ('sub',
                                                              ('var',
                                                               'n_points'),
                                                              ('num', 1))),
                                                            ('slice_item',
                                                             ('num', 2),
                                                             ('var',
                                                              'n_points'))]),
                                                          ('indexN',
                                                           'f',
                                                           [('slice_item',
                                                             ('num', 1),
                                                             ('sub',
                                                              ('var',
                                                               'n_points'),
                                                              ('num', 1))),
                                                            ('slice_item',
                                                             ('num', 0),
                                                             ('sub',
                                                              ('var',
                                                               'n_points'),
                                                              ('num', 2)))])),
                                                         ('mul',
                                                          ('num', 2),
                                                          ('var',
                                                           'element_length'))))]},
               'central_difference_y': {'params': [('f',
                                                    ('tensor',
                                                     [('m', 'invariant'),
                                                      ('n', 'invariant')]))],
                                        'return_type': ('tensor',
                                                        [('m', 'invariant'),
                                                         ('n', 'invariant')]),
                                        'body': ('var', 'diff'),
                                        'has_loop': False,
                                        'statements': [('body_decl',
                                                        'diff',
                                                        ('tensor',
                                                         [('n_points',
                                                           'invariant'),
                                                          ('n_points',
                                                           'invariant')]),
                                                        ('call',
                                                         'zero_2d_array',
                                                         [('var', 'n_points'),
                                                          ('var',
                                                           'n_points')])),
                                                       ('body_index_assign_nd',
                                                        'diff',
                                                        [('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'n_points'),
                                                           ('num', 1))),
                                                         ('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'n_points'),
                                                           ('num', 1)))],
                                                        ('div',
                                                         ('sub',
                                                          ('indexN',
                                                           'f',
                                                           [('slice_item',
                                                             ('num', 2),
                                                             ('var',
                                                              'n_points')),
                                                            ('slice_item',
                                                             ('num', 1),
                                                             ('sub',
                                                              ('var',
                                                               'n_points'),
                                                              ('num', 1)))]),
                                                          ('indexN',
                                                           'f',
                                                           [('slice_item',
                                                             ('num', 0),
                                                             ('sub',
                                                              ('var',
                                                               'n_points'),
                                                              ('num', 2))),
                                                            ('slice_item',
                                                             ('num', 1),
                                                             ('sub',
                                                              ('var',
                                                               'n_points'),
                                                              ('num', 1)))])),
                                                         ('mul',
                                                          ('num', 2),
                                                          ('var',
                                                           'element_length'))))]},
               'laplace': {'params': [('f',
                                       ('tensor',
                                        [('m', 'invariant'),
                                         ('n', 'invariant')]))],
                           'return_type': ('tensor',
                                           [('m', 'invariant'),
                                            ('n', 'invariant')]),
                           'body': ('var', 'diff'),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'diff',
                                           ('tensor',
                                            [('n_points', 'invariant'),
                                             ('n_points', 'invariant')]),
                                           ('call',
                                            'zero_2d_array',
                                            [('var', 'n_points'),
                                             ('var', 'n_points')])),
                                          ('body_index_assign_nd',
                                           'diff',
                                           [('slice_item',
                                             ('num', 1),
                                             ('sub',
                                              ('var', 'n_points'),
                                              ('num', 1))),
                                            ('slice_item',
                                             ('num', 1),
                                             ('sub',
                                              ('var', 'n_points'),
                                              ('num', 1)))],
                                           ('div',
                                            ('sub',
                                             ('add',
                                              ('add',
                                               ('add',
                                                ('indexN',
                                                 'f',
                                                 [('slice_item',
                                                   ('num', 1),
                                                   ('sub',
                                                    ('var', 'n_points'),
                                                    ('num', 1))),
                                                  ('slice_item',
                                                   ('num', 0),
                                                   ('sub',
                                                    ('var', 'n_points'),
                                                    ('num', 2)))]),
                                                ('indexN',
                                                 'f',
                                                 [('slice_item',
                                                   ('num', 0),
                                                   ('sub',
                                                    ('var', 'n_points'),
                                                    ('num', 2))),
                                                  ('slice_item',
                                                   ('num', 1),
                                                   ('sub',
                                                    ('var', 'n_points'),
                                                    ('num', 1)))])),
                                               ('indexN',
                                                'f',
                                                [('slice_item',
                                                  ('num', 1),
                                                  ('sub',
                                                   ('var', 'n_points'),
                                                   ('num', 1))),
                                                 ('slice_item',
                                                  ('num', 2),
                                                  ('var', 'n_points'))])),
                                              ('indexN',
                                               'f',
                                               [('slice_item',
                                                 ('num', 2),
                                                 ('var', 'n_points')),
                                                ('slice_item',
                                                 ('num', 1),
                                                 ('sub',
                                                  ('var', 'n_points'),
                                                  ('num', 1)))])),
                                             ('mul',
                                              ('num', 4),
                                              ('indexN',
                                               'f',
                                               [('slice_item',
                                                 ('num', 1),
                                                 ('sub',
                                                  ('var', 'n_points'),
                                                  ('num', 1))),
                                                ('slice_item',
                                                 ('num', 1),
                                                 ('sub',
                                                  ('var', 'n_points'),
                                                  ('num', 1)))]))),
                                            ('pow',
                                             ('var', 'element_length'),
                                             ('num', 2))))]},
               'solver': {'params': [('ρ', 'ℝ')],
                          'return_type': ('tensor',
                                          [(3, 'invariant'),
                                           ('m', 'invariant'),
                                           ('n', 'invariant')]),
                          'body': ('array',
                                   [('var', 'u_prev'),
                                    ('var', 'v_prev'),
                                    ('var', 'p_prev')]),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'u_prev',
                                          ('tensor',
                                           [('n_points', 'invariant'),
                                            ('n_points', 'invariant')]),
                                          ('call',
                                           'zero_2d_array',
                                           [('var', 'n_points'),
                                            ('var', 'n_points')])),
                                         ('body_decl',
                                          'v_prev',
                                          ('tensor',
                                           [('n_points', 'invariant'),
                                            ('n_points', 'invariant')]),
                                          ('call',
                                           'zero_2d_array',
                                           [('var', 'n_points'),
                                            ('var', 'n_points')])),
                                         ('body_decl',
                                          'p_prev',
                                          ('tensor',
                                           [('n_points', 'invariant'),
                                            ('n_points', 'invariant')]),
                                          ('call',
                                           'zero_2d_array',
                                           [('var', 'n_points'),
                                            ('var', 'n_points')])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'n_iterations'),
                                          [('loop_assign',
                                            'd_u_prev__d_x',
                                            ('call',
                                             'central_difference_x',
                                             [('var', 'u_prev')])),
                                           ('loop_assign',
                                            'd_u_prev__d_y',
                                            ('call',
                                             'central_difference_y',
                                             [('var', 'u_prev')])),
                                           ('loop_assign',
                                            'd_v_prev__d_x',
                                            ('call',
                                             'central_difference_x',
                                             [('var', 'v_prev')])),
                                           ('loop_assign',
                                            'd_v_prev__d_y',
                                            ('call',
                                             'central_difference_y',
                                             [('var', 'v_prev')])),
                                           ('loop_assign',
                                            'laplace__u_prev',
                                            ('call',
                                             'laplace',
                                             [('var', 'u_prev')])),
                                           ('loop_assign',
                                            'laplace__v_prev',
                                            ('call',
                                             'laplace',
                                             [('var', 'v_prev')])),
                                           ('loop_assign',
                                            'u_tent',
                                            ('add',
                                             ('var', 'u_prev'),
                                             ('mul',
                                              ('var', 'time_step_length'),
                                              ('add',
                                               ('neg',
                                                ('add',
                                                 ('mul',
                                                  ('var', 'u_prev'),
                                                  ('var', 'd_u_prev__d_x')),
                                                 ('mul',
                                                  ('var', 'v_prev'),
                                                  ('var', 'd_u_prev__d_y')))),
                                               ('mul',
                                                ('var', 'ν'),
                                                ('var', 'laplace__u_prev')))))),
                                           ('loop_assign',
                                            'v_tent',
                                            ('add',
                                             ('var', 'v_prev'),
                                             ('mul',
                                              ('var', 'time_step_length'),
                                              ('add',
                                               ('neg',
                                                ('add',
                                                 ('mul',
                                                  ('var', 'u_prev'),
                                                  ('var', 'd_v_prev__d_x')),
                                                 ('mul',
                                                  ('var', 'v_prev'),
                                                  ('var', 'd_v_prev__d_y')))),
                                               ('mul',
                                                ('var', 'ν'),
                                                ('var', 'laplace__v_prev')))))),
                                           ('loop_index_assign_nd',
                                            'u_tent',
                                            [('index_item', ('num', 0)),
                                             ('slice_item', None, None)],
                                            ('num', 0.0)),
                                           ('loop_index_assign_nd',
                                            'u_tent',
                                            [('index_item',
                                              ('neg', ('num', 1))),
                                             ('slice_item', None, None)],
                                            ('var', 'horizontal_velocity_top')),
                                           ('loop_index_assign_nd',
                                            'u_tent',
                                            [('slice_item', None, None),
                                             ('index_item', ('num', 0))],
                                            ('num', 0.0)),
                                           ('loop_index_assign_nd',
                                            'u_tent',
                                            [('slice_item', None, None),
                                             ('index_item',
                                              ('neg', ('num', 1)))],
                                            ('num', 0.0)),
                                           ('loop_index_assign_nd',
                                            'v_tent',
                                            [('index_item', ('num', 0)),
                                             ('slice_item', None, None)],
                                            ('num', 0.0)),
                                           ('loop_index_assign_nd',
                                            'v_tent',
                                            [('index_item',
                                              ('neg', ('num', 1))),
                                             ('slice_item', None, None)],
                                            ('num', 0.0)),
                                           ('loop_index_assign_nd',
                                            'v_tent',
                                            [('slice_item', None, None),
                                             ('index_item', ('num', 0))],
                                            ('num', 0.0)),
                                           ('loop_index_assign_nd',
                                            'v_tent',
                                            [('slice_item', None, None),
                                             ('index_item',
                                              ('neg', ('num', 1)))],
                                            ('num', 0.0)),
                                           ('loop_assign',
                                            'd_u_tent__d_x',
                                            ('call',
                                             'central_difference_x',
                                             [('var', 'u_tent')])),
                                           ('loop_assign',
                                            'd_v_tent__d_y',
                                            ('call',
                                             'central_difference_y',
                                             [('var', 'v_tent')])),
                                           ('loop_assign',
                                            'rhs',
                                            ('mul',
                                             ('div',
                                              ('var', 'ρ'),
                                              ('var', 'time_step_length')),
                                             ('add',
                                              ('var', 'd_u_tent__d_x'),
                                              ('var', 'd_v_tent__d_y')))),
                                           ('loop_for_range',
                                            'k',
                                            ('num', 0),
                                            ('var',
                                             'n_pressure_poisson_iterations'),
                                            [('loop_assign',
                                              'p_next',
                                              ('call',
                                               'zero_2d_array',
                                               [('var', 'n_points'),
                                                ('var', 'n_points')])),
                                             ('loop_index_assign_nd',
                                              'p_next',
                                              [('slice_item',
                                                ('num', 1),
                                                ('neg', ('num', 1))),
                                               ('slice_item',
                                                ('num', 1),
                                                ('neg', ('num', 1)))],
                                              ('mul',
                                               ('num', 0.25),
                                               ('sub',
                                                ('add',
                                                 ('add',
                                                  ('add',
                                                   ('indexN',
                                                    'p_prev',
                                                    [('slice_item',
                                                      ('num', 1),
                                                      ('neg', ('num', 1))),
                                                     ('slice_item',
                                                      None,
                                                      ('neg', ('num', 2)))]),
                                                   ('indexN',
                                                    'p_prev',
                                                    [('slice_item',
                                                      None,
                                                      ('neg', ('num', 2))),
                                                     ('slice_item',
                                                      ('num', 1),
                                                      ('neg', ('num', 1)))])),
                                                  ('indexN',
                                                   'p_prev',
                                                   [('slice_item',
                                                     ('num', 1),
                                                     ('neg', ('num', 1))),
                                                    ('slice_item',
                                                     ('num', 2),
                                                     None)])),
                                                 ('indexN',
                                                  'p_prev',
                                                  [('slice_item',
                                                    ('num', 2),
                                                    None),
                                                   ('slice_item',
                                                    ('num', 1),
                                                    ('neg', ('num', 1)))])),
                                                ('mul',
                                                 ('pow',
                                                  ('var', 'element_length'),
                                                  ('num', 2)),
                                                 ('indexN',
                                                  'rhs',
                                                  [('slice_item',
                                                    ('num', 1),
                                                    ('neg', ('num', 1))),
                                                   ('slice_item',
                                                    ('num', 1),
                                                    ('neg', ('num', 1)))]))))),
                                             ('loop_index_assign_nd',
                                              'p_next',
                                              [('slice_item', None, None),
                                               ('index_item',
                                                ('neg', ('num', 1)))],
                                              ('indexN',
                                               'p_next',
                                               [('slice_item', None, None),
                                                ('index_item',
                                                 ('neg', ('num', 2)))])),
                                             ('loop_index_assign_nd',
                                              'p_next',
                                              [('index_item', ('num', 0)),
                                               ('slice_item', None, None)],
                                              ('indexN',
                                               'p_next',
                                               [('index_item', ('num', 1)),
                                                ('slice_item', None, None)])),
                                             ('loop_index_assign_nd',
                                              'p_next',
                                              [('slice_item', None, None),
                                               ('index_item', ('num', 0))],
                                              ('indexN',
                                               'p_next',
                                               [('slice_item', None, None),
                                                ('index_item', ('num', 1))])),
                                             ('loop_index_assign_nd',
                                              'p_next',
                                              [('index_item',
                                                ('neg', ('num', 1))),
                                               ('slice_item', None, None)],
                                              ('num', 0.0)),
                                             ('loop_assign',
                                              'p_prev',
                                              ('var', 'p_next'))]),
                                           ('loop_assign',
                                            'd_p_next__d_x',
                                            ('call',
                                             'central_difference_x',
                                             [('var', 'p_next')])),
                                           ('loop_assign',
                                            'd_p_next__d_y',
                                            ('call',
                                             'central_difference_y',
                                             [('var', 'p_next')])),
                                           ('loop_assign',
                                            'u_next',
                                            ('sub',
                                             ('var', 'u_tent'),
                                             ('mul',
                                              ('div',
                                               ('var', 'time_step_length'),
                                               ('var', 'ρ')),
                                              ('var', 'd_p_next__d_x')))),
                                           ('loop_assign',
                                            'v_next',
                                            ('sub',
                                             ('var', 'v_tent'),
                                             ('mul',
                                              ('div',
                                               ('var', 'time_step_length'),
                                               ('var', 'ρ')),
                                              ('var', 'd_p_next__d_y')))),
                                           ('loop_index_assign_nd',
                                            'u_next',
                                            [('index_item', ('num', 0)),
                                             ('slice_item', None, None)],
                                            ('num', 0.0)),
                                           ('loop_index_assign_nd',
                                            'u_next',
                                            [('slice_item', None, None),
                                             ('index_item', ('num', 0))],
                                            ('num', 0.0)),
                                           ('loop_index_assign_nd',
                                            'u_next',
                                            [('slice_item', None, None),
                                             ('index_item',
                                              ('neg', ('num', 1)))],
                                            ('num', 0.0)),
                                           ('loop_index_assign_nd',
                                            'u_next',
                                            [('index_item',
                                              ('neg', ('num', 1))),
                                             ('slice_item', None, None)],
                                            ('var', 'horizontal_velocity_top')),
                                           ('loop_index_assign_nd',
                                            'v_next',
                                            [('index_item', ('num', 0)),
                                             ('slice_item', None, None)],
                                            ('num', 0.0)),
                                           ('loop_index_assign_nd',
                                            'v_next',
                                            [('slice_item', None, None),
                                             ('index_item', ('num', 0))],
                                            ('num', 0.0)),
                                           ('loop_index_assign_nd',
                                            'v_next',
                                            [('slice_item', None, None),
                                             ('index_item',
                                              ('neg', ('num', 1)))],
                                            ('num', 0.0)),
                                           ('loop_index_assign_nd',
                                            'v_next',
                                            [('index_item',
                                              ('neg', ('num', 1))),
                                             ('slice_item', None, None)],
                                            ('num', 0.0)),
                                           ('loop_assign',
                                            'u_prev',
                                            ('var', 'u_next')),
                                           ('loop_assign',
                                            'v_prev',
                                            ('var', 'v_next')),
                                           ('loop_assign',
                                            'p_prev',
                                            ('var', 'p_next'))])]},
               'calculate_loss': {'params': [('ρ', 'ℝ')],
                                  'return_type': 'ℝ',
                                  'body': ('var', 'loss'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'predictions',
                                                  ('tensor',
                                                   [(3, 'invariant'),
                                                    ('n_points', 'invariant'),
                                                    ('n_points', 'invariant')]),
                                                  ('call',
                                                   'solver',
                                                   [('var', 'ρ')])),
                                                 ('body_decl',
                                                  'pred_u',
                                                  ('tensor',
                                                   [('n_points', 'invariant'),
                                                    ('n_points', 'invariant')]),
                                                  ('index',
                                                   'predictions',
                                                   ('num', 0))),
                                                 ('body_decl',
                                                  'pred_v',
                                                  ('tensor',
                                                   [('n_points', 'invariant'),
                                                    ('n_points', 'invariant')]),
                                                  ('index',
                                                   'predictions',
                                                   ('num', 1))),
                                                 ('body_decl',
                                                  'pred_p',
                                                  ('tensor',
                                                   [('n_points', 'invariant'),
                                                    ('n_points', 'invariant')]),
                                                  ('index',
                                                   'predictions',
                                                   ('num', 2))),
                                                 ('body_decl',
                                                  'loss_u',
                                                  'ℝ',
                                                  ('call',
                                                   'mean',
                                                   [('pow',
                                                     ('sub',
                                                      ('var', 'pred_u'),
                                                      ('var', 'true_u')),
                                                     ('num', 2))])),
                                                 ('body_decl',
                                                  'loss_v',
                                                  'ℝ',
                                                  ('call',
                                                   'mean',
                                                   [('pow',
                                                     ('sub',
                                                      ('var', 'pred_v'),
                                                      ('var', 'true_v')),
                                                     ('num', 2))])),
                                                 ('body_decl',
                                                  'loss_p',
                                                  'ℝ',
                                                  ('call',
                                                   'mean',
                                                   [('pow',
                                                     ('sub',
                                                      ('var', 'pred_p'),
                                                      ('var', 'true_p')),
                                                     ('num', 2))])),
                                                 ('body_decl',
                                                  'loss',
                                                  'ℝ',
                                                  ('add',
                                                   ('add',
                                                    ('var', 'loss_u'),
                                                    ('var', 'loss_v')),
                                                   ('var', 'loss_p')))]},
               'adam': {'params': [('ρ', 'ℝ'),
                                   ('g', 'ℝ'),
                                   ('m', 'ℝ'),
                                   ('v', 'ℝ'),
                                   ('t', 'ℝ'),
                                   ('lr', 'ℝ')],
                        'return_type': ('tensor', [(4, 'invariant')]),
                        'body': ('array',
                                 [('var', 'ρ_new'),
                                  ('var', 'm_new'),
                                  ('var', 'v_new'),
                                  ('add', ('var', 't'), ('num', 1.0))]),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        'beta1',
                                        'ℝ',
                                        ('num', 0.9)),
                                       ('body_decl',
                                        'beta2',
                                        'ℝ',
                                        ('num', 0.999)),
                                       ('body_decl',
                                        'eps',
                                        'ℝ',
                                        ('num', 1e-08)),
                                       ('body_decl',
                                        'm_new',
                                        'ℝ',
                                        ('add',
                                         ('mul',
                                          ('var', 'beta1'),
                                          ('var', 'm')),
                                         ('mul',
                                          ('sub',
                                           ('num', 1.0),
                                           ('var', 'beta1')),
                                          ('var', 'g')))),
                                       ('body_decl',
                                        'v_new',
                                        'ℝ',
                                        ('add',
                                         ('mul',
                                          ('var', 'beta2'),
                                          ('var', 'v')),
                                         ('mul',
                                          ('sub',
                                           ('num', 1.0),
                                           ('var', 'beta2')),
                                          ('pow', ('var', 'g'), ('num', 2))))),
                                       ('body_decl',
                                        'm_hat',
                                        'ℝ',
                                        ('div',
                                         ('var', 'm_new'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow',
                                           ('var', 'beta1'),
                                           ('var', 't'))))),
                                       ('body_decl',
                                        'v_hat',
                                        'ℝ',
                                        ('div',
                                         ('var', 'v_new'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow',
                                           ('var', 'beta2'),
                                           ('var', 't'))))),
                                       ('body_decl',
                                        'ρ_new',
                                        'ℝ',
                                        ('sub',
                                         ('var', 'ρ'),
                                         ('div',
                                          ('mul',
                                           ('var', 'lr'),
                                           ('var', 'm_hat')),
                                          ('add',
                                           ('call', 'sqrt', [('var', 'v_hat')]),
                                           ('var', 'eps')))))]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'linspace'),
             ('func_def', 'zero_2d_array'),
             ('decl', 'n_points', 'ℝ', ('num', 21), 26),
             ('decl', 'domain_size', 'ℝ', ('num', 1.0), 27),
             ('decl', 'n_iterations', 'ℝ', ('num', 500), 28),
             ('decl', 'time_step_length', 'ℝ', ('num', 0.001), 30),
             ('decl', 'ν', 'ℝ', ('num', 0.1), 31),
             ('decl', 'true_ρ', 'ℝ', ('num', 1.0), 32),
             ('decl', 'horizontal_velocity_top', 'ℝ', ('num', 1.0), 33),
             ('decl', 'n_pressure_poisson_iterations', 'ℝ', ('num', 10), 35),
             ('decl', 'stability_safety_factor', 'ℝ', ('num', 0.5), 36),
             ('decl',
              'element_length',
              'ℝ',
              ('div',
               ('var', 'domain_size'),
               ('sub', ('var', 'n_points'), ('num', 1))),
              38),
             ('decl',
              'x',
              ('tensor', [('n_points', 'invariant')]),
              ('call',
               'linspace',
               [('num', 0.0), ('var', 'domain_size'), ('var', 'n_points')]),
              40),
             ('decl',
              'y',
              ('tensor', [('n_points', 'invariant')]),
              ('call',
               'linspace',
               [('num', 0.0), ('var', 'domain_size'), ('var', 'n_points')]),
              41),
             ('func_def', 'central_difference_x'),
             ('func_def', 'central_difference_y'),
             ('func_def', 'laplace'),
             ('decl',
              'f',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('call',
               'zero_2d_array',
               [('var', 'n_points'), ('var', 'n_points')]),
              80),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'n_points'),
              [('for_loop_range',
                'j',
                ('num', 0),
                ('var', 'n_points'),
                [('for_assign',
                  't_x',
                  ('mul', ('var', 'j'), ('var', 'element_length'))),
                 ('for_assign',
                  't_y',
                  ('mul', ('imaginary',), ('var', 'element_length'))),
                 ('for_index_assign_nd',
                  'f',
                  [('index_item', ('imaginary',)),
                   ('index_item', ('var', 'j'))],
                  ('add',
                   ('pow', ('var', 't_x'), ('num', 2)),
                   ('pow', ('var', 't_y'), ('num', 2))))],
                83)],
              82),
             ('decl', 'n_iterations', 'ℝ', ('num', 5), 94),
             ('func_def', 'solver'),
             ('decl',
              'true_solution',
              ('tensor',
               [(3, 'invariant'),
                ('n_points', 'invariant'),
                ('n_points', 'invariant')]),
              ('call', 'solver', [('var', 'true_ρ')]),
              172),
             ('decl',
              'true_u',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('index', 'true_solution', ('num', 0)),
              173),
             ('decl',
              'true_v',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('index', 'true_solution', ('num', 1)),
              174),
             ('decl',
              'true_p',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('index', 'true_solution', ('num', 2)),
              175),
             ('func_def', 'calculate_loss'),
             ('func_def', 'adam'),
             ('decl', 'ρ', 'ℝ', ('num', 3.0), 213),
             ('decl', 'm_adam', 'ℝ', ('num', 0.0), 215),
             ('decl', 'v_adam', 'ℝ', ('num', 0.0), 216),
             ('decl', 't_adam', 'ℝ', ('num', 1.0), 217),
             ('decl', 'lr', 'ℝ', ('num', 0.01), 218),
             ('decl', 'epochs', 'ℕ', ('num', 1), 225),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_call', 'physika_print', [('imaginary',)]),
               ('for_assign',
                'g',
                ('call', 'grad', [('var', 'calculate_loss'), ('var', 'ρ')])),
               ('for_assign',
                'result',
                ('call',
                 'adam',
                 [('var', 'ρ'),
                  ('var', 'g'),
                  ('var', 'm_adam'),
                  ('var', 'v_adam'),
                  ('var', 't_adam'),
                  ('var', 'lr')])),
               ('for_assign', 'ρ', ('index', 'result', ('num', 0))),
               ('for_assign', 'm_adam', ('index', 'result', ('num', 1))),
               ('for_assign', 'v_adam', ('index', 'result', ('num', 2))),
               ('for_assign', 't_adam', ('index', 'result', ('num', 3))),
               ('for_call', 'physika_print', [('var', 'ρ')])],
              227),
             ('expr', ('var', 'ρ'), 0),
             ('decl',
              'pred_solution',
              ('tensor',
               [(3, 'invariant'),
                ('n_points', 'invariant'),
                ('n_points', 'invariant')]),
              ('call', 'solver', [('var', 'ρ')]),
              245),
             ('decl',
              'pred_u',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('index', 'pred_solution', ('num', 0)),
              246),
             ('decl',
              'pred_v',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('index', 'pred_solution', ('num', 1)),
              247),
             ('decl',
              'pred_p',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('index', 'pred_solution', ('num', 2)),
              248),
             ('decl',
              'X',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('call',
               'zero_2d_array',
               [('var', 'n_points'), ('var', 'n_points')]),
              251),
             ('decl',
              'Y',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('call',
               'zero_2d_array',
               [('var', 'n_points'), ('var', 'n_points')]),
              252),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'n_points'),
              [('for_loop_range',
                'j',
                ('num', 0),
                ('var', 'n_points'),
                [('for_index_assign_nd',
                  'X',
                  [('index_item', ('imaginary',)),
                   ('index_item', ('var', 'j'))],
                  ('mul', ('var', 'j'), ('var', 'element_length'))),
                 ('for_index_assign_nd',
                  'Y',
                  [('index_item', ('imaginary',)),
                   ('index_item', ('var', 'j'))],
                  ('mul', ('imaginary',), ('var', 'element_length')))],
                255)],
              254)]}
