EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'linspace': {'params': [('start', 'ℝ'),
                                       ('end', 'ℝ'),
                                       ('n', 'ℕ')],
                            'return_type': ('tensor', [('n', 'invariant')]),
                            'body': ('var', 'x'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'x',
                                            ('tensor', [('n', 'invariant')]),
                                            ('call',
                                             'zero_1d_array',
                                             [('var', 'n')])),
                                           ('body_decl',
                                            'Δx',
                                            'ℝ',
                                            ('div',
                                             ('sub',
                                              ('var', 'end'),
                                              ('var', 'start')),
                                             ('sub',
                                              ('var', 'n'),
                                              ('num', 1)))),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('var', 'n'),
                                            [('loop_index_assign_nd',
                                              'x',
                                              [('index_item', ('imaginary',))],
                                              ('add',
                                               ('var', 'start'),
                                               ('mul',
                                                ('imaginary',),
                                                ('var', 'Δx'))))])]},
               'heat_equation': {'params': [('T',
                                             ('tensor',
                                              [('m', 'invariant'),
                                               ('n', 'invariant')])),
                                            ('Δx', 'ℝ'),
                                            ('Δy', 'ℝ'),
                                            ('α', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'f'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'f',
                                                 ('tensor',
                                                  [('m', 'invariant'),
                                                   ('n', 'invariant')]),
                                                 ('call',
                                                  'zero_2d_array',
                                                  [('var', 'nx'),
                                                   ('var', 'ny')])),
                                                ('body_index_assign_nd',
                                                 'f',
                                                 [('slice_item',
                                                   ('num', 1),
                                                   ('sub',
                                                    ('var', 'nx'),
                                                    ('num', 1))),
                                                  ('slice_item',
                                                   ('num', 1),
                                                   ('sub',
                                                    ('var', 'ny'),
                                                    ('num', 1)))],
                                                 ('mul',
                                                  ('var', 'α'),
                                                  ('add',
                                                   ('div',
                                                    ('add',
                                                     ('sub',
                                                      ('indexN',
                                                       'T',
                                                       [('slice_item',
                                                         ('num', 0),
                                                         ('sub',
                                                          ('var', 'nx'),
                                                          ('num', 2))),
                                                        ('slice_item',
                                                         ('num', 1),
                                                         ('sub',
                                                          ('var', 'ny'),
                                                          ('num', 1)))]),
                                                      ('mul',
                                                       ('num', 2),
                                                       ('indexN',
                                                        'T',
                                                        [('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'nx'),
                                                           ('num', 1))),
                                                         ('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'ny'),
                                                           ('num', 1)))]))),
                                                     ('indexN',
                                                      'T',
                                                      [('slice_item',
                                                        ('num', 2),
                                                        ('var', 'nx')),
                                                       ('slice_item',
                                                        ('num', 1),
                                                        ('sub',
                                                         ('var', 'ny'),
                                                         ('num', 1)))])),
                                                    ('pow',
                                                     ('var', 'Δx'),
                                                     ('num', 2))),
                                                   ('div',
                                                    ('add',
                                                     ('sub',
                                                      ('indexN',
                                                       'T',
                                                       [('slice_item',
                                                         ('num', 1),
                                                         ('sub',
                                                          ('var', 'nx'),
                                                          ('num', 1))),
                                                        ('slice_item',
                                                         ('num', 0),
                                                         ('sub',
                                                          ('var', 'ny'),
                                                          ('num', 2)))]),
                                                      ('mul',
                                                       ('num', 2),
                                                       ('indexN',
                                                        'T',
                                                        [('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'nx'),
                                                           ('num', 1))),
                                                         ('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'ny'),
                                                           ('num', 1)))]))),
                                                     ('indexN',
                                                      'T',
                                                      [('slice_item',
                                                        ('num', 1),
                                                        ('sub',
                                                         ('var', 'nx'),
                                                         ('num', 1))),
                                                       ('slice_item',
                                                        ('num', 2),
                                                        ('var', 'ny'))])),
                                                    ('pow',
                                                     ('var', 'Δy'),
                                                     ('num', 2))))))]},
               'solver': {'params': [('α', 'ℝ'),
                                     ('T0',
                                      ('tensor',
                                       [('m', 'invariant'),
                                        ('n', 'invariant')])),
                                     ('Δx', 'ℝ'),
                                     ('Δy', 'ℝ'),
                                     ('Δt', 'ℝ'),
                                     ('nt', 'ℝ')],
                          'return_type': ('tensor',
                                          [('m', 'invariant'),
                                           ('n', 'invariant')]),
                          'body': ('var', 'T'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'T',
                                          ('tensor',
                                           [('m', 'invariant'),
                                            ('n', 'invariant')]),
                                          ('var', 'T0')),
                                         ('body_for_range',
                                          'step',
                                          ('num', 0),
                                          ('var', 'nt'),
                                          [('loop_assign',
                                            'T',
                                            ('add',
                                             ('var', 'T'),
                                             ('mul',
                                              ('var', 'Δt'),
                                              ('call',
                                               'heat_equation',
                                               [('var', 'T'),
                                                ('var', 'Δx'),
                                                ('var', 'Δy'),
                                                ('var', 'α')])))),
                                           ('loop_index_assign_nd',
                                            'T',
                                            [('slice_item', None, None),
                                             ('index_item', ('num', 0))],
                                            ('num', 0)),
                                           ('loop_index_assign_nd',
                                            'T',
                                            [('slice_item', None, None),
                                             ('index_item',
                                              ('sub',
                                               ('var', 'ny'),
                                               ('num', 1)))],
                                            ('num', 0)),
                                           ('loop_index_assign_nd',
                                            'T',
                                            [('index_item', ('num', 0)),
                                             ('slice_item', None, None)],
                                            ('num', 0)),
                                           ('loop_index_assign_nd',
                                            'T',
                                            [('index_item',
                                              ('sub',
                                               ('var', 'nx'),
                                               ('num', 1))),
                                             ('slice_item', None, None)],
                                            ('num', 0))])]},
               'calculate_loss': {'params': [('α', 'ℝ')],
                                  'return_type': 'ℝ',
                                  'body': ('var', 'loss'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'predictions',
                                                  ('tensor',
                                                   [('nx', 'invariant'),
                                                    ('ny', 'invariant')]),
                                                  ('call',
                                                   'solver',
                                                   [('var', 'α'),
                                                    ('var', 'T0'),
                                                    ('var', 'Δx'),
                                                    ('var', 'Δy'),
                                                    ('var', 'Δt'),
                                                    ('var', 'nt')])),
                                                 ('body_decl',
                                                  'diff',
                                                  ('tensor',
                                                   [('nx', 'invariant'),
                                                    ('ny', 'invariant')]),
                                                  ('sub',
                                                   ('var', 'predictions'),
                                                   ('var', 'true_solution'))),
                                                 ('body_decl',
                                                  'loss',
                                                  'ℝ',
                                                  ('call',
                                                   'mean',
                                                   [('pow',
                                                     ('var', 'diff'),
                                                     ('num', 2))]))]},
               'adam': {'params': [('α', 'ℝ'),
                                   ('g', 'ℝ'),
                                   ('m', 'ℝ'),
                                   ('v', 'ℝ'),
                                   ('t', 'ℝ'),
                                   ('lr', 'ℝ')],
                        'return_type': ('tensor', [(4, 'invariant')]),
                        'body': ('array',
                                 [('var', 'α_new'),
                                  ('var', 'm_new'),
                                  ('var', 'v_new'),
                                  ('add', ('var', 't'), ('num', 1.0))]),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        'beta1',
                                        'ℝ',
                                        ('num', 0.9)),
                                       ('body_decl',
                                        'beta2',
                                        'ℝ',
                                        ('num', 0.999)),
                                       ('body_decl',
                                        'eps',
                                        'ℝ',
                                        ('num', 1e-08)),
                                       ('body_decl',
                                        'm_new',
                                        'ℝ',
                                        ('add',
                                         ('mul',
                                          ('var', 'beta1'),
                                          ('var', 'm')),
                                         ('mul',
                                          ('sub',
                                           ('num', 1.0),
                                           ('var', 'beta1')),
                                          ('var', 'g')))),
                                       ('body_decl',
                                        'v_new',
                                        'ℝ',
                                        ('add',
                                         ('mul',
                                          ('var', 'beta2'),
                                          ('var', 'v')),
                                         ('mul',
                                          ('sub',
                                           ('num', 1.0),
                                           ('var', 'beta2')),
                                          ('pow', ('var', 'g'), ('num', 2))))),
                                       ('body_decl',
                                        'm_hat',
                                        'ℝ',
                                        ('div',
                                         ('var', 'm_new'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow',
                                           ('var', 'beta1'),
                                           ('var', 't'))))),
                                       ('body_decl',
                                        'v_hat',
                                        'ℝ',
                                        ('div',
                                         ('var', 'v_new'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow',
                                           ('var', 'beta2'),
                                           ('var', 't'))))),
                                       ('body_decl',
                                        'α_new',
                                        'ℝ',
                                        ('sub',
                                         ('var', 'α'),
                                         ('div',
                                          ('mul',
                                           ('var', 'lr'),
                                           ('var', 'm_hat')),
                                          ('add',
                                           ('call', 'sqrt', [('var', 'v_hat')]),
                                           ('var', 'eps')))))]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'zero_2d_array'),
             ('func_def', 'linspace'),
             ('decl', 'true_α', 'ℝ', ('num', 2.0), 27),
             ('decl', 'Lx', 'ℝ', ('num', 1.0), 28),
             ('decl', 'Ly', 'ℝ', ('num', 1.0), 29),
             ('decl', 'nx', 'ℝ', ('num', 40), 31),
             ('decl', 'ny', 'ℝ', ('num', 40), 32),
             ('decl', 'tf', 'ℝ', ('num', 10), 33),
             ('decl',
              'Δx',
              'ℝ',
              ('div', ('var', 'Lx'), ('sub', ('var', 'nx'), ('num', 1))),
              35),
             ('decl',
              'Δy',
              'ℝ',
              ('div', ('var', 'Ly'), ('sub', ('var', 'ny'), ('num', 1))),
              36),
             ('decl', 'fourier', 'ℝ', ('num', 0.49), 43),
             ('decl',
              'Δt',
              'ℝ',
              ('div',
               ('div',
                ('var', 'fourier'),
                ('add',
                 ('pow', ('div', ('num', 1), ('var', 'Δx')), ('num', 2)),
                 ('pow', ('div', ('num', 1), ('var', 'Δy')), ('num', 2)))),
               ('num', 10.0)),
              44),
             ('decl', 'nt', 'ℝ', ('num', 100), 45),
             ('stmt_tuple_unpack',
              [('T1', 'ℝ'), ('T2', 'ℝ'), ('T3', 'ℝ'), ('T4', 'ℝ')],
              ('expr_list', [('num', 0), ('num', 0), ('num', 0), ('num', 0)])),
             ('decl',
              'x',
              ('tensor', [('nx', 'invariant')]),
              ('call', 'linspace', [('num', 0), ('var', 'Lx'), ('var', 'nx')]),
              58),
             ('decl',
              'y',
              ('tensor', [('ny', 'invariant')]),
              ('call', 'linspace', [('num', 0), ('var', 'Ly'), ('var', 'ny')]),
              59),
             ('decl',
              'T0',
              ('tensor', [('nx', 'invariant'), ('ny', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'nx'),
               ('for_expr',
                'j',
                ('var', 'ny'),
                ('call',
                 'exp',
                 [('mul',
                   ('neg', ('num', 20)),
                   ('add',
                    ('pow',
                     ('sub', ('index', 'x', ('imaginary',)), ('num', 0.5)),
                     ('num', 2)),
                    ('pow',
                     ('sub', ('index', 'y', ('var', 'j')), ('num', 0.5)),
                     ('num', 2))))]))),
              67),
             ('func_def', 'heat_equation'),
             ('func_def', 'solver'),
             ('decl',
              'true_solution',
              ('tensor', [('nx', 'invariant'), ('ny', 'invariant')]),
              ('call',
               'solver',
               [('var', 'true_α'),
                ('var', 'T0'),
                ('var', 'Δx'),
                ('var', 'Δy'),
                ('var', 'Δt'),
                ('var', 'nt')]),
              98),
             ('func_def', 'calculate_loss'),
             ('func_def', 'adam'),
             ('decl', 'α', 'ℝ', ('num', 4.0), 132),
             ('decl',
              'guess_solution',
              ('tensor', [('nx', 'invariant'), ('ny', 'invariant')]),
              ('call',
               'solver',
               [('var', 'α'),
                ('var', 'T0'),
                ('var', 'Δx'),
                ('var', 'Δy'),
                ('var', 'Δt'),
                ('var', 'nt')]),
              134),
             ('decl', 'm_adam', 'ℝ', ('num', 0.0), 137),
             ('decl', 'v_adam', 'ℝ', ('num', 0.0), 138),
             ('decl', 't_adam', 'ℝ', ('num', 1.0), 139),
             ('decl', 'lr', 'ℝ', ('num', 0.01), 140),
             ('decl', 'epochs', 'ℕ', ('num', 1), 147),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_call', 'physika_print', [('imaginary',)]),
               ('for_assign',
                'g',
                ('call', 'grad', [('var', 'calculate_loss'), ('var', 'α')])),
               ('for_assign',
                'result',
                ('call',
                 'adam',
                 [('var', 'α'),
                  ('var', 'g'),
                  ('var', 'm_adam'),
                  ('var', 'v_adam'),
                  ('var', 't_adam'),
                  ('var', 'lr')])),
               ('for_assign', 'α', ('index', 'result', ('num', 0))),
               ('for_assign', 'm_adam', ('index', 'result', ('num', 1))),
               ('for_assign', 'v_adam', ('index', 'result', ('num', 2))),
               ('for_assign', 't_adam', ('index', 'result', ('num', 3))),
               ('for_call', 'physika_print', [('var', 'α')])],
              149),
             ('expr', ('var', 'α'), 0),
             ('decl',
              'pred_solution',
              ('tensor', [('nx', 'invariant'), ('ny', 'invariant')]),
              ('call',
               'solver',
               [('var', 'α'),
                ('var', 'T0'),
                ('var', 'Δx'),
                ('var', 'Δy'),
                ('var', 'Δt'),
                ('var', 'nt')]),
              162)]}
