EXPECTED = {'functions': {'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'linspace': {'params': [('start', 'ℝ'),
                                       ('end', 'ℝ'),
                                       ('n', 'ℕ')],
                            'return_type': ('tensor', [('n', 'invariant')]),
                            'body': ('var', 'x'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'x',
                                            ('tensor', [('n', 'invariant')]),
                                            ('call',
                                             'zero_1d_array',
                                             [('var', 'n')])),
                                           ('body_decl',
                                            'Δx',
                                            'ℝ',
                                            ('div',
                                             ('sub',
                                              ('var', 'end'),
                                              ('var', 'start')),
                                             ('sub',
                                              ('var', 'n'),
                                              ('num', 1)))),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('var', 'n'),
                                            [('loop_index_assign_nd',
                                              'x',
                                              [('index_item', ('imaginary',))],
                                              ('add',
                                               ('var', 'start'),
                                               ('mul',
                                                ('imaginary',),
                                                ('var', 'Δx'))))])]},
               'wave_equation': {'params': [('u',
                                             ('tensor',
                                              [('m', 'invariant'),
                                               ('n', 'invariant')])),
                                            ('Δx', 'ℝ'),
                                            ('Δy', 'ℝ'),
                                            ('c', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'lap'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'lap',
                                                 ('tensor',
                                                  [('m', 'invariant'),
                                                   ('n', 'invariant')]),
                                                 ('call',
                                                  'zero_2d_array',
                                                  [('var', 'nx'),
                                                   ('var', 'ny')])),
                                                ('body_index_assign_nd',
                                                 'lap',
                                                 [('slice_item',
                                                   ('num', 1),
                                                   ('sub',
                                                    ('var', 'nx'),
                                                    ('num', 1))),
                                                  ('slice_item',
                                                   ('num', 1),
                                                   ('sub',
                                                    ('var', 'ny'),
                                                    ('num', 1)))],
                                                 ('mul',
                                                  ('pow',
                                                   ('var', 'c'),
                                                   ('num', 2)),
                                                  ('add',
                                                   ('div',
                                                    ('add',
                                                     ('sub',
                                                      ('indexN',
                                                       'u',
                                                       [('slice_item',
                                                         ('num', 0),
                                                         ('sub',
                                                          ('var', 'nx'),
                                                          ('num', 2))),
                                                        ('slice_item',
                                                         ('num', 1),
                                                         ('sub',
                                                          ('var', 'ny'),
                                                          ('num', 1)))]),
                                                      ('mul',
                                                       ('num', 2),
                                                       ('indexN',
                                                        'u',
                                                        [('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'nx'),
                                                           ('num', 1))),
                                                         ('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'ny'),
                                                           ('num', 1)))]))),
                                                     ('indexN',
                                                      'u',
                                                      [('slice_item',
                                                        ('num', 2),
                                                        ('var', 'nx')),
                                                       ('slice_item',
                                                        ('num', 1),
                                                        ('sub',
                                                         ('var', 'ny'),
                                                         ('num', 1)))])),
                                                    ('pow',
                                                     ('var', 'Δx'),
                                                     ('num', 2))),
                                                   ('div',
                                                    ('add',
                                                     ('sub',
                                                      ('indexN',
                                                       'u',
                                                       [('slice_item',
                                                         ('num', 1),
                                                         ('sub',
                                                          ('var', 'nx'),
                                                          ('num', 1))),
                                                        ('slice_item',
                                                         ('num', 0),
                                                         ('sub',
                                                          ('var', 'ny'),
                                                          ('num', 2)))]),
                                                      ('mul',
                                                       ('num', 2),
                                                       ('indexN',
                                                        'u',
                                                        [('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'nx'),
                                                           ('num', 1))),
                                                         ('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'ny'),
                                                           ('num', 1)))]))),
                                                     ('indexN',
                                                      'u',
                                                      [('slice_item',
                                                        ('num', 1),
                                                        ('sub',
                                                         ('var', 'nx'),
                                                         ('num', 1))),
                                                       ('slice_item',
                                                        ('num', 2),
                                                        ('var', 'ny'))])),
                                                    ('pow',
                                                     ('var', 'Δy'),
                                                     ('num', 2))))))]},
               'solver': {'params': [('c', 'ℝ'),
                                     ('u0',
                                      ('tensor',
                                       [('m', 'invariant'),
                                        ('n', 'invariant')])),
                                     ('v0',
                                      ('tensor',
                                       [('m', 'invariant'),
                                        ('n', 'invariant')])),
                                     ('Δx', 'ℝ'),
                                     ('Δy', 'ℝ'),
                                     ('Δt', 'ℝ'),
                                     ('nt', 'ℝ')],
                          'return_type': ('tensor',
                                          [('m', 'invariant'),
                                           ('n', 'invariant')]),
                          'body': ('var', 'u_curr'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'u_prev',
                                          ('tensor',
                                           [('m', 'invariant'),
                                            ('n', 'invariant')]),
                                          ('var', 'u0')),
                                         ('body_decl',
                                          'u_curr',
                                          ('tensor',
                                           [('m', 'invariant'),
                                            ('n', 'invariant')]),
                                          ('var', 'u0')),
                                         ('body_for_range',
                                          'step',
                                          ('num', 0),
                                          ('var', 'nt'),
                                          [('loop_assign',
                                            'accel',
                                            ('call',
                                             'wave_equation',
                                             [('var', 'u_curr'),
                                              ('var', 'Δx'),
                                              ('var', 'Δy'),
                                              ('var', 'c')])),
                                           ('loop_assign',
                                            'u_next',
                                            ('add',
                                             ('sub',
                                              ('mul',
                                               ('num', 2),
                                               ('var', 'u_curr')),
                                              ('var', 'u_prev')),
                                             ('mul',
                                              ('pow',
                                               ('var', 'Δt'),
                                               ('num', 2)),
                                              ('var', 'accel')))),
                                           ('loop_index_assign_nd',
                                            'u_next',
                                            [('slice_item', None, None),
                                             ('index_item', ('num', 0))],
                                            ('num', 0)),
                                           ('loop_index_assign_nd',
                                            'u_next',
                                            [('slice_item', None, None),
                                             ('index_item',
                                              ('sub',
                                               ('var', 'ny'),
                                               ('num', 1)))],
                                            ('num', 0)),
                                           ('loop_index_assign_nd',
                                            'u_next',
                                            [('index_item', ('num', 0)),
                                             ('slice_item', None, None)],
                                            ('num', 0)),
                                           ('loop_index_assign_nd',
                                            'u_next',
                                            [('index_item',
                                              ('sub',
                                               ('var', 'nx'),
                                               ('num', 1))),
                                             ('slice_item', None, None)],
                                            ('num', 0)),
                                           ('loop_assign',
                                            'u_prev',
                                            ('var', 'u_curr')),
                                           ('loop_assign',
                                            'u_curr',
                                            ('var', 'u_next'))])]},
               'calculate_loss': {'params': [('c', 'ℝ')],
                                  'return_type': 'ℝ',
                                  'body': ('var', 'loss'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'predictions',
                                                  ('tensor',
                                                   [('nx', 'invariant'),
                                                    ('ny', 'invariant')]),
                                                  ('call',
                                                   'solver',
                                                   [('var', 'c'),
                                                    ('var', 'u0'),
                                                    ('var', 'v0'),
                                                    ('var', 'Δx'),
                                                    ('var', 'Δy'),
                                                    ('var', 'Δt'),
                                                    ('var', 'nt')])),
                                                 ('body_decl',
                                                  'diff',
                                                  ('tensor',
                                                   [('nx', 'invariant'),
                                                    ('ny', 'invariant')]),
                                                  ('sub',
                                                   ('var', 'predictions'),
                                                   ('var', 'true_solution'))),
                                                 ('body_decl',
                                                  'loss',
                                                  'ℝ',
                                                  ('call',
                                                   'mean',
                                                   [('pow',
                                                     ('var', 'diff'),
                                                     ('num', 2))]))]},
               'adam': {'params': [('c', 'ℝ'),
                                   ('g', 'ℝ'),
                                   ('m', 'ℝ'),
                                   ('v', 'ℝ'),
                                   ('t', 'ℝ'),
                                   ('lr', 'ℝ')],
                        'return_type': ('tensor', [(4, 'invariant')]),
                        'body': ('array',
                                 [('var', 'c_new'),
                                  ('var', 'm_new'),
                                  ('var', 'v_new'),
                                  ('add', ('var', 't'), ('num', 1.0))]),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        'beta1',
                                        'ℝ',
                                        ('num', 0.9)),
                                       ('body_decl',
                                        'beta2',
                                        'ℝ',
                                        ('num', 0.999)),
                                       ('body_decl',
                                        'eps',
                                        'ℝ',
                                        ('num', 1e-08)),
                                       ('body_decl',
                                        'm_new',
                                        'ℝ',
                                        ('add',
                                         ('mul',
                                          ('var', 'beta1'),
                                          ('var', 'm')),
                                         ('mul',
                                          ('sub',
                                           ('num', 1.0),
                                           ('var', 'beta1')),
                                          ('var', 'g')))),
                                       ('body_decl',
                                        'v_new',
                                        'ℝ',
                                        ('add',
                                         ('mul',
                                          ('var', 'beta2'),
                                          ('var', 'v')),
                                         ('mul',
                                          ('sub',
                                           ('num', 1.0),
                                           ('var', 'beta2')),
                                          ('pow', ('var', 'g'), ('num', 2))))),
                                       ('body_decl',
                                        'm_hat',
                                        'ℝ',
                                        ('div',
                                         ('var', 'm_new'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow',
                                           ('var', 'beta1'),
                                           ('var', 't'))))),
                                       ('body_decl',
                                        'v_hat',
                                        'ℝ',
                                        ('div',
                                         ('var', 'v_new'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow',
                                           ('var', 'beta2'),
                                           ('var', 't'))))),
                                       ('body_decl',
                                        'c_new',
                                        'ℝ',
                                        ('sub',
                                         ('var', 'c'),
                                         ('div',
                                          ('mul',
                                           ('var', 'lr'),
                                           ('var', 'm_hat')),
                                          ('add',
                                           ('call', 'sqrt', [('var', 'v_hat')]),
                                           ('var', 'eps')))))]}},
 'classes': {},
 'program': [('func_def', 'get_1d_array_length'),
             ('func_def', 'zero_1d_array'),
             ('func_def', 'zero_2d_array'),
             ('func_def', 'linspace'),
             ('decl', 'Lx', 'ℝ', ('num', 1.0), 33),
             ('decl', 'Ly', 'ℝ', ('num', 1.0), 34),
             ('decl', 'nx', 'ℝ', ('num', 40), 35),
             ('decl', 'ny', 'ℝ', ('num', 40), 36),
             ('decl', 'tf', 'ℝ', ('num', 2.0), 37),
             ('decl',
              'Δx',
              'ℝ',
              ('div', ('var', 'Lx'), ('sub', ('var', 'nx'), ('num', 1))),
              39),
             ('decl',
              'Δy',
              'ℝ',
              ('div', ('var', 'Ly'), ('sub', ('var', 'ny'), ('num', 1))),
              40),
             ('decl', 'true_c', 'ℝ', ('num', 1.0), 42),
             ('decl', 'cfl', 'ℝ', ('num', 0.4), 48),
             ('decl',
              'Δt',
              'ℝ',
              ('div',
               ('var', 'cfl'),
               ('mul',
                ('num', 5.0),
                ('call',
                 'sqrt',
                 [('add',
                   ('pow', ('div', ('num', 1), ('var', 'Δx')), ('num', 2)),
                   ('pow', ('div', ('num', 1), ('var', 'Δy')), ('num', 2)))]))),
              49),
             ('decl', 'nt', 'ℝ', ('num', 50), 50),
             ('decl',
              'x',
              ('tensor', [('nx', 'invariant')]),
              ('call', 'linspace', [('num', 0), ('var', 'Lx'), ('var', 'nx')]),
              56),
             ('decl',
              'y',
              ('tensor', [('ny', 'invariant')]),
              ('call', 'linspace', [('num', 0), ('var', 'Ly'), ('var', 'ny')]),
              57),
             ('decl', 'pi', 'ℝ', ('num', 3.14), 59),
             ('decl',
              'u0',
              ('tensor', [('nx', 'invariant'), ('ny', 'invariant')]),
              ('call', 'zero_2d_array', [('var', 'nx'), ('var', 'ny')]),
              60),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'nx'),
              [('for_loop_range',
                'j',
                ('num', 0),
                ('var', 'ny'),
                [('for_index_assign_nd',
                  'u0',
                  [('index_item', ('imaginary',)),
                   ('index_item', ('var', 'j'))],
                  ('mul',
                   ('call',
                    'sin',
                    [('mul',
                      ('mul', ('num', 2), ('var', 'pi')),
                      ('index', 'x', ('imaginary',)))]),
                   ('call',
                    'sin',
                    [('mul', ('var', 'pi'), ('index', 'y', ('var', 'j')))])))],
                63)],
              62),
             ('decl',
              'v0',
              ('tensor', [('nx', 'invariant'), ('ny', 'invariant')]),
              ('call', 'zero_2d_array', [('var', 'nx'), ('var', 'ny')]),
              66),
             ('func_def', 'wave_equation'),
             ('func_def', 'solver'),
             ('decl',
              'true_solution',
              ('tensor', [('nx', 'invariant'), ('ny', 'invariant')]),
              ('call',
               'solver',
               [('var', 'true_c'),
                ('var', 'u0'),
                ('var', 'v0'),
                ('var', 'Δx'),
                ('var', 'Δy'),
                ('var', 'Δt'),
                ('var', 'nt')]),
              99),
             ('func_def', 'calculate_loss'),
             ('func_def', 'adam'),
             ('decl', 'c', 'ℝ', ('num', 3.0), 131),
             ('decl', 'm_adam', 'ℝ', ('num', 0.0), 134),
             ('decl', 'v_adam', 'ℝ', ('num', 0.0), 135),
             ('decl', 't_adam', 'ℝ', ('num', 1.0), 136),
             ('decl', 'lr', 'ℝ', ('num', 0.01), 137),
             ('decl', 'epochs', 'ℕ', ('num', 1), 144),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_call', 'physika_print', [('imaginary',)]),
               ('for_assign',
                'g',
                ('call', 'grad', [('var', 'calculate_loss'), ('var', 'c')])),
               ('for_assign',
                'result',
                ('call',
                 'adam',
                 [('var', 'c'),
                  ('var', 'g'),
                  ('var', 'm_adam'),
                  ('var', 'v_adam'),
                  ('var', 't_adam'),
                  ('var', 'lr')])),
               ('for_assign', 'c', ('index', 'result', ('num', 0))),
               ('for_assign', 'm_adam', ('index', 'result', ('num', 1))),
               ('for_assign', 'v_adam', ('index', 'result', ('num', 2))),
               ('for_assign', 't_adam', ('index', 'result', ('num', 3))),
               ('for_call', 'physika_print', [('var', 'c')])],
              147),
             ('decl',
              'pred_solution',
              ('tensor', [('nx', 'invariant'), ('ny', 'invariant')]),
              ('call',
               'solver',
               [('var', 'c'),
                ('var', 'u0'),
                ('var', 'v0'),
                ('var', 'Δx'),
                ('var', 'Δy'),
                ('var', 'Δt'),
                ('var', 'nt')]),
              157)]}
